### ISSUE TITLE
bug: Directories scan never ends on v2.0.2

### ISSUE THREAD

**Issue by DrorDvash** [yogeshojha/rengine#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've updated reNgine to version 2.0.2 after I saw a closed issue where ffuf results were fixed and are now shown in the dashboard UI. This issue seems to be resolved, and the results are presented. However, the scan running never ends or keeps running over and over again.

Scan type: Subdomain Discovery, Port Scan, Directory and Files Search
![image](https://github.com/yogeshojha/rengine/assets/8413651/55cee238-ecce-4c96-b4ce-cd4c74da8830)

Current scan running for 23 hours (in v1.3.6 **the same** scan finished in 30-50 minutes)
![image](https://github.com/yogeshojha/rengine/assets/8413651/44855703-49ce-493d-81e0-1cc19d43dc76)

When looking at the results, I noticed that each subdomain was scanned multiple times for directory fuzzing (ffuf) instead of just once.
![image](https://github.com/yogeshojha/rengine/assets/8413651/1dfc0f7b-984b-4036-a991-64bc07a48961)

### Expected Behavior

Each domain should be scanned 1 time only with ffuf, and the scan should end correctly.

### Steps To Reproduce

1. Create Custom (quick) scan engine:
```yaml
subdomain_discovery: {
  'uses_tools': ['subfinder', 'ctfr', 'sublist3r', 'tlsx', 'oneforall', 'netlas'],
  'enable_http_crawl': true,
  'threads': 30,
  'timeout': 5,
}
http_crawl: {}
port_scan: {
  'enable_http_crawl': true,
  'timeout': 5,
  # 'exclude_ports': [],
  # 'exclude_subdomains': [],
  'ports': ['top-100'],
  'rate_limit': 150,
  'threads': 30,
  'passive': false,
  # 'use_naabu_config': false,
  # 'enable_nmap': true,
  # 'nmap_cmd': '',
  # 'nmap_script': '',
  # 'nmap_script_args': ''
}
dir_file_fuzz: {
  'auto_calibration': true,
  'enable_http_crawl': true,
  'rate_limit': 150,
  'extensions': ['html', 'php','git','yaml','conf','cnf','config','gz','env','log','db','mysql','bak','asp','aspx','txt','conf','sql','json','yml','pdf'],
  'follow_redirect': false,
  'max_time': 0,
  'match_http_status': [200, 204],
  'recursive_level': 2,
  'stop_on_error': false,
  'timeout': 5,
  'threads': 30,
  'wordlist_name': 'dicc'
}
screenshot: {
  'enable_http_crawl': true,
  'intensity': 'normal',
  'timeout': 10,
  'threads': 40
}

# custom_header: "Cookie: Test"
```

2. Start a new scan using the above engine.

### Environment

```markdown
- reNgine: v2.0.2
- OS: Ubuntu 22.04
- Python: Python 3.10.12
- Docker Engine: 24.0.7
- Docker Compose: v2.21.0
```

### Anything else?

If any logs are needed, please specify which ones and provide instructions on how to extract them for you. (I used `make logs`, but there are numerous lines.)

Thank you.
