### ISSUE TITLE
bug: theHarvester not picking up api-keys configured in Tool Settings

### ISSUE THREAD

**Issue by b1k3** [yogeshojha/rengine#1451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a scan Harvester is not picking up any API keys configured within the Tool Setting page of the application

### Expected Behavior

When configuring the settings for theHarvester within Tool Settings of the GUI and then running a scan it should utilise the API keys provided.

### Steps To Reproduce

1. Log into reNgine GUI
2.  Go to Settings > Tools Settings.
3. Double Click on the configuration for theHarvester
4. Enter the yaml configuration as required:

```
apikeys:
  bevigil:
    key:

  binaryedge:
    key:

  bing:
    key:

  bufferoverun:
    key:

  censys:
    id:
    secret:

  criminalip:
    key:

  fullhunt:
    key:

  github:
    key:

  hunter:
    key:

  hunterhow:
    key:

  intelx:
    key:

  netlas:
    key:

  onyphe:
    key:

  pentestTools:
    key:

  projectDiscovery:
    key:

  rocketreach:
    key:

  securityTrails:
    key: <key goes here>

  shodan:
    key:

  tomba:
    key:
    secret:

  virustotal:
    key: <key goes here>
```
5. Click Save Changes
6. Configure Target
7. Run Scan (Tested OSINT Scan)

### Environment

```markdown
- reNgine: 2.2.0
- OS: Ubuntu 24.04
- Python: 3.12.3
- Docker Engine: 27.3.1
- Docker Compose: N/A
- Browser: Chrome 129.0.6668.70
```

### Anything else?

When the scan runs and theHarvester is run, it attempts to pick up the api-keys.yaml file from `/root/.theHarvester/api-keys.yaml` as per screenshot below:

![image](https://github.com/user-attachments/assets/90127528-68d8-4d5a-aef1-aa5e7c50978e)

When connecting to the celery container and checking the file, no keys are saved in this file.

Connecting to the celery docker container `rengine-celery-1` using `sudo docker exec -it rengine-celery-1 /bin/bash`, I located that the file in the below location `/usr/src/github/theHarvester/api-keys.yaml` is the file updated by the GUI.

As a work around I've copied the `/usr/src/github/theHarvester/api-keys.yaml` to the one in the `/root/.theHarvester/` location.
