### ISSUE TITLE
How to exclude 403 from dirsearch?

### ISSUE THREAD

**Issue by ptrk01** [yogeshojha/rengine#265]
Does anyone know how to exclude 403 findings from dirsearch? I often get thousands of them listed in the results. 

Found this in /rengine/tools/default_settings.yaml:

```
dir_file_search:
    extensions: [ php,asp,aspx,txt,conf,db,sql,json ]
    recursive: false
    recursive_level: 1
    thread: 100
    wordlist: default
```

But not sure how to add the exclusion. Any idea?
