### ISSUE TITLE
Amass Configurations never work for me

### ISSUE THREAD

**Issue by bahlawi89** [yogeshojha/rengine#299]
### Issue Summary

I found out when I set a new configuration for Amass and load it with my custom scan Engine, it never calls any API at all. 

### Steps to Reproduce

1. Create a new configuration called "amass_config_temp"
2. Create a new scan engine and call for "amass_config_temp" using ( amass_config: amass_config_temp)
3. Start a new Scan using your newly created scan engine.
4. Check if any calls to the API have been requested by visiting API provider like VirusTotal and see if there are any new calls made by amass.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes)

### Technical details
Scan Engine: 

```
subdomain_discovery:
    uses_tool: [ all ]
    thread: 10
    wordlist: default
    amass_config: amass_config_temp
    subfinder_config: subfinder_config_temp


visual_identification:
    port: small
    thread: 10
    http_timeout: 30000
    screenshot_timeout: 300000
    scan_timeout: 10000

fetch_url:
    uses_tool: [all]
    intensity: aggressive

vulnerability_scan:
    concurrent: 50
    template: [all]
    severity: [critical, high, medium]
```

***************************************************************
amass_config_temp: 

```
port=443
 
[data_sources.AlienVault]
[data_sources.AlienVault.Credentials]
apikey = ddddddddddddd

#https://app.binaryedge.com (Free)
[data_sources.BinaryEdge]
ttl = 10080
[data_sources.BinaryEdge.Credentials]
apikey = dddd-dddd-dddd-dddd-ddddddddd

#https://virustotal.com (Free)
[data_sources.VirusTotal]
ttl = 10080
[data_sources.VirusTotal.Credentials]
apikey = dddddddddddddddddddddddddddddddddddddd
```
