### ISSUE TITLE
Basic Auth for rengine

### ISSUE THREAD

**Issue by pradeepch99** [yogeshojha/rengine#324]
I have added basic authentication for nginx proxy with below configuration

```
sudo apt-get update
sudo apt-get install apache2-utils
```

```
cd rengine/config/nginx
sudo htpasswd -c .htpasswd USERNAME
```
You will be asked to supply and confirm a password for the user.

`nano rengine/docker-compose.yml`

Add auth file volume as below under proxy:

```
    proxy:
        restart: always
        image: nginx:alpine
        ports:
            - 80:80/tcp
            - 443:443/tcp
        depends_on:
            - web
            - db
            - redis
        secrets:
            - source: proxy.ca
              target: /etc/nginx/certs/rengine_chain.pem
            - source: proxy.cert
              target: /etc/nginx/certs/rengine.pem
            - source: proxy.key
              target: /etc/nginx/certs/rengine_rsa.key
        volumes:
            - ./config/nginx/rengine.conf:/etc/nginx/conf.d/rengine.conf:ro
            - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
            - static_volume:/app/staticfiles
            - media_volume:/app/tools/scan_results
        networks:
            - rengine_network
```
