### ISSUE TITLE
vulnerability_scan failed to achieve expected results

### ISSUE THREAD

**Issue by prettyrecon** [yogeshojha/rengine#380]
I use this template。

```
subdomain_discovery:
    uses_tool: [ subfinder, oneforall ]
    thread: 10

vulnerability_scan:
    concurrent: 10
    template: [all]
    severity: [ critical, high, medium ]
```

**But I get the result of severity of info vulnerabilities.**

![image](https://user-images.githubusercontent.com/79907007/113707039-eb215300-9711-11eb-8653-5135fb2e7626.png)
