### ISSUE TITLE
Bug - After modification of YAML, server gives out error 500

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#588]
### Issue Summary

For rEngine recommended, YAML was modified accordingly:
```
subdomain_discovery:
  uses_tools: [ amass-passive, assetfinder, sublist3r, subfinder, oneforall ]
  threads: 10
  use_amass_config: false
  use_subfinder_config: false

visual_identification:
  timeout: 10
  threads: 5

osint:
  discover: [ emails, metainfo, employees ]
  intensity: normal
  # intensity: deep
  dork: [ stackoverflow, 3rdparty, social_media, project_management, code_sharing, config_files, jenkins, wordpress_files, cloud_buckets, php_error, exposed_documents, struts_rce, db_files, traefik, git_exposed ]

port_scan:
  ports: [ top-100 ]
  rate: 1000
  use_naabu_config: false
  # exclude_ports: [80, 8080]

dir_file_search:
  extensions: [ php, git, yaml, conf, db, mysql, bak, asp, aspx, txt, conf, sql, json ]
  threads: 100
  recursive: false
  recursive_level: 1
  wordlist: default

fetch_url:
  uses_tools: [ gauplus, hakrawler, waybackurls, gospider ]
  intensity: normal
  # intensity: deep
  ignore_file_extension: [jpg, png, jpeg, gif]
  gf_patterns: [ debug_logic, idor, img-traversal, interestingEXT, interestingparams, interestingsubs, jsvar, lfi, rce, redirect, sqli, ssrf, ssti, xss]

vulnerability_scan:
  concurrency: 10
  rate_limit: 150
  timeout: 5
  retries: 1
  templates: [ all ]
  # custom_templates: []
  severity: [ critical, high, medium, low, info ]
```

### Steps to Reproduce

1. Modify the YAML to aforementioned
2. Try to start rEngine Recommended engine for a target
3. Get server error 500

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details
Ubuntu 20.04.4 LTS
